version: "3.1"

services: 
  bot-server:
    image: bot-server
    build: 
      context: "./"
    restart: "no"
    volumes:
      - ./:/usr/src/app
    networks: 
      - bot-network
    environment: 
      - APP_ENV=${APP_ENV}
      - TZ=America/Argentina/Buenos_Aires
    ports: 
      - ${BOT_SERVER_PORT}:${BOT_SERVER_PORT}

networks:
  bot-network:
    driver: bridge
