version: "3.1"

services: 
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - ./data:/data/db
    ports:
      - ${MONGO_LOCAL_PORT}:27017
    networks:
      - bot-network
  bot-server:
    image: bot-server
    build: 
      context: "./"
      dockerfile: "./Dockerfiles/node/Dockerfile"
    restart: always
    volumes:
      - ./:/usr/src/app
    networks: 
      - bot-network
    environment: 
      - APP_ENV=${APP_ENV}
      - TZ=America/Argentina/Buenos_Aires
    ports: 
      - ${BOT_SERVER_PORT}:3010

networks:
  bot-network:
    driver: bridge
